Repository tranquilitybase-io/tb-eagle-console, pull requests merged in 2020-10, with the labels that each got.

#295 Patch/#294/create activator modal error handling
  src/app/mission-control/activator-store/activator-store-dialog/activator-store-dialog-create/activator-store-dialog-create.component.ts
  src/app/mission-control/activator-store/activator-store.actions.ts
  src/app/mission-control/activator-store/activator-store.reducer.ts
  src/app/mission-control/activator-store/activator-store.service.ts
  src/app/shared/shared.module.ts
  src/app/shared/snack-bar/activator-create-error/activator-create-error.component.html
  src/app/shared/snack-bar/activator-create-error/activator-create-error.component.scss
  src/app/shared/snack-bar/activator-create-error/activator-create-error.component.spec.ts
  src/app/shared/snack-bar/activator-create-error/activator-create-error.component.ts
  src/app/shared/snack-bar/activator-create-success/activator-create-success.component.html
  src/app/shared/snack-bar/activator-create-success/activator-create-success.component.scss
  src/app/shared/snack-bar/activator-create-success/activator-create-success.component.spec.ts
  src/app/shared/snack-bar/activator-create-success/activator-create-success.component.ts
Labels: Activators

#305 disabled all inputs when solution is deployed
  src/app/mission-control/solutions/solutions-edit/solutions-edit.component.html
Labels: bug

#332 Issue 321
  src/app/mission-control/solutions/solutions-create/solutions-create.component.html
  src/app/mission-control/solutions/solutions-create/solutions-create.component.scss
  src/app/mission-control/solutions/solutions-create/solutions-create.component.ts
  src/app/mission-control/solutions/solutions-create/solutions-create.module.ts
  src/app/mission-control/solutions/solutions-edit/solutions-edit.component.html
  src/app/mission-control/solutions/solutions-edit/solutions-edit.component.ts
  src/app/mission-control/solutions/solutions-edit/solutions-edit.module.ts
  src/app/mission-control/solutions/solutions-home/solutions-home-grid/solutions-home-grid-card/solutions-home-grid-card.component.html
  src/app/mission-control/solutions/solutions-home/solutions-home-list/solutions-home-list.component.html
  src/app/mission-control/solutions/solutions-home/solutions-home-list/solutions-home-list.component.ts
  src/app/mission-control/solutions/solutions-view/solutions-view-overview/solutions-view-overview.component.html
  src/app/mission-control/solutions/solutions-view/solutions-view-overview/solutions-view-overview.component.scss
  src/app/mission-control/solutions/solutions.model.ts
  src/app/shared/layout/layout.service.ts
Labels: Sandbox
