Repository tranquilitybase-io/tb-eagle-console, pull requests merged in 2021-05, with the labels that each got.

#508 Prepare Activator Store graphic layout to match Landing Zone layout
  .github/release-drafter.yml
  src/app/mission-control/activator-store/activator-store-home/activator-store-home-category-grid/activator-store-home-category-grid.component.html
  src/app/mission-control/activator-store/activator-store-home/activator-store-home-category-grid/activator-store-home-category-grid.component.scss
  src/app/mission-control/activator-store/activator-store-home/activator-store-home-category-grid/activator-store-home-category-grid.component.ts
  src/app/mission-control/activator-store/activator-store-home/activator-store-home.module.ts
Labels: type: ux/ui update

#507 Fix Burger menu misbehavior
  src/app/layout/layout.component.html
  src/app/layout/layout.component.scss
  src/app/layout/layout.component.ts
  src/app/mission-control/activator-store/activator-store-dialog/activator-store-dialog-missing-solutions/activator-store-dialog-missing-solutions.component.ts
  src/app/mission-control/activator-store/activator-store.component.scss
  src/app/shared/welcome/welcome.component.html
Labels: type: ux/ui update

#499 Dividing of isAdmin flag to LZ Admin and MC Admin
  src/app/administration/administration.module.ts
  src/app/administration/team-members/team-members-container/team-members-container.component.html
  src/app/administration/team-members/team-members-container/team-members-container.component.ts
  src/app/administration/team-members/team-members-grid/team-members-grid.component.ts
  src/app/administration/team-members/team-members-list/team-members-list.component.ts
  src/app/administration/users/users.model.ts
  src/app/guards/lz-admin-guard.service.ts
  src/app/layout/layout.component.html
  src/app/layout/layout.component.ts
  src/app/login/login.model.ts
  src/app/login/login.reducer.ts
  src/app/mission-control/activator-store/activator-store-home/activator-store-home-grid/activator-store-home-grid-card/activator-store-home-grid-card.component.html
  src/app/mission-control/activator-store/activator-store-home/activator-store-home-grid/activator-store-home-grid-card/activator-store-home-grid-card.component.ts
  src/app/mission-control/activator-store/activator-store-home/activator-store-home-grid/activator-store-home-grid.component.ts
  src/app/mission-control/activator-store/activator-store-home/activator-store-home-list/activator-store-home-list.component.html
  src/app/mission-control/activator-store/activator-store-home/activator-store-home-list/activator-store-home-list.component.ts
  src/app/mission-control/activator-store/activator-store-home/activator-store-home.component.html
  src/app/mission-control/activator-store/activator-store-home/activator-store-home.component.ts
  src/app/mission-control/activator-store/activator-store-view/activator-store-view.component.html
  src/app/mission-control/activator-store/activator-store-view/activator-store-view.component.ts
  src/app/mission-control/applications/applications-grid/applications-grid.component.ts
  src/app/mission-control/solutions/solutions-view/solutions-view-applications/solutions-view-applications.component.ts
  src/app/mission-control/solutions/solutions-view/solutions-view.component.html
  src/app/mission-control/solutions/solutions-view/solutions-view.component.ts
  src/app/shared/welcome/welcome.component.html
  src/app/shared/welcome/welcome.component.ts
Labels: type: feature

#530 #529 Fix multiple API calls in Solution View screen
  src/app/mission-control/solutions/solutions-view/solutions-view.component.ts
  src/app/mission-control/solutions/solutions-view/solutions-view.module.ts
Labels: type: bug

#528 Add stepper for provisioning Activators into Solutions starting the workflow from the ActivatorStore
  src/app/mission-control/activator-store/activator-store-home/activator-store-home.component.html
  src/app/mission-control/applications/applications-create/applications-create-review/applications-create-review.component.html
  src/app/mission-control/applications/applications-create/applications-create-review/applications-create-review.component.scss
  src/app/mission-control/applications/applications-create/applications-create-review/applications-create-review.component.ts
  src/app/mission-control/applications/applications-create/applications-create.component.html
  src/app/mission-control/applications/applications-create/applications-create.component.scss
  src/app/mission-control/applications/applications-create/applications-create.component.ts
Labels: type: feature
